=== dmisiuk/by.minsler.htp/src/xml/pl.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pointlist (point*)>
<!ELEMENT point (x,y)>
<!ATTLIST point unit (cm|px|mm) #REQUIRED>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>

=== dmisiuk/by.minsler.htp/src/nextlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pointlist SYSTEM "pl.dtd">
<pointlist>
	<point unit="cm">
		<x>23</x>
		<y>18</y>
	</point>
	<point unit="px">
		<x>2394</x>
		<y>23121</y>
	</point>
	<point unit="mm">
		<x>17</x>
		<y>11</y>
	</point>
	<point unit="px">
		<x>90</x>
		<y>0</y>
	</point>

</pointlist>
